### ISSUE TITLE
crash while compile with  -On

### ISSUE THREAD

**Issue by niu2x** [nfrechette/rtm#65]
rtm::matrix_from_translation
crash on this call. if i compile with -O1~8.

gdb said:
Thread 1 "gxm" received signal SIGSEGV, Segmentation fault.
0x0000555555568dee in Transform::Transform (this=0x5555559d44a8) at src/core/transform.cpp:6
6		mat3x4 = rtm::matrix_from_translation(v);

**Comment by nfrechette** [comment]
What compiler/platform are you using?
What compiler arguments are you using?
Could you provide the assembly for rtm::matrix_from_translation and which instruction the crash happens on?

Thanks!

**Comment by nfrechette** [comment]
I will be closing this issue due to lack of information/activity. `rtm::matrix_from_translation` does very little work, the most likely reason for a segmentation fault here would come from an improper cast from a `float3` type object into a `vector4f` which is not safe if there is no padding present. Use `rtm::vector_load3` and related functions to ensure safe construction of vectors that might not have padding.

For example, if you have an array of multiple `float3` objects. Loading the every element but the last would be safe with a simple cast (the loads might not be aligned but on x64 it might not matter). However, the element may or may not crash if you load it in the same manner if the last float ends up on a page boundary where the next memory page isn't mapped. Attempting to load 16 bytes would cause us to attempt to load the last 4 bytes from an unmapped page, triggering an access violation (or segmentation fault).
